name: tflite
description: A Flutter plugin for accessing TensorFlow Lite. Supports both iOS and Android.
version: 1.1.3
homepage: https://github.com/SrilalS/flutter_tflite

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: sq.flutter.tflite
        pluginClass: TflitePlugin